create database nota;

use nota;

create table if not exists nota(
id_not int primary key auto_increment,
nome varchar(200),
ent1 char(4),
ent2 char(4),
ent3 char(4),
resultado varchar(20)
);
insert into primeiro(nome) values('Italo');

SELECT * FROM primeiro;



create table if not exists primeiro(
id_primeiro int primary key auto_increment,
nome varchar(200),
atv1_1 char(4),
atv2_2 char(4),
atv3_3 char(4),
resultado_av1 varchar(20),
atv2_1 char(4),
atv2_2_2 char(4),
atv2_3 char(4),
resultado_av2 varchar(20),
resultado_usinadade1 varchar(20),

atv3_1 char(4),
atv3_2 char(4),
atv3_3_3 char(4),
resultado_av3 varchar(20),
atv4_1 char(4),
atv4_2 char(4),
atv4_3 char(4),
resultado_av4 varchar(20),
resultado_usinadade2 varchar(20),
atv5_1 char(4),
atv5_2 char(4),
atv5_3 char(4),
resultado_av5 varchar(20),
atv6_1 char(4),
atv6_2 char(4),
atv6_3 char(4),
resultado_av6 varchar(20),
resultado_usinadade3 varchar(20),
resultado_final varchar(50)
);
SELECT * 
create table if not exists segundo(
id_primeiro int primary key auto_increment,
nome varchar(200),
atv1_1 char(4),
atv2_2 char(4),
atv3_3 char(4),
resultado_av1 varchar(20),
atv2_1 char(4),
atv2_2_2 char(4),
atv2_3 char(4),
resultado_av2 varchar(20),
resultado_usinadade1 varchar(20),
atv3_1 char(4),
atv3_2 char(4),
atv3_3_3 char(4),
resultado_av3 varchar(20),
atv4_1 char(4),
atv4_2 char(4),
atv4_3 char(4),
resultado_av4 varchar(20),
resultado_usinadade2 varchar(20),
atv5_1 char(4),
atv5_2 char(4),
atv5_3 char(4),
resultado_av5 varchar(20),
atv6_1 char(4),
atv6_2 char(4),
atv6_3 char(4),
resultado_av6 varchar(20),
resultado_usinadade3 varchar(20),
resultado_final varchar(50)
);

create table if not exists terceito(
id_primeiro int primary key auto_increment,
nome varchar(200),
atv1_1 char(4),
atv2_2 char(4),
atv3_3 char(4),
resultado_av1 varchar(20),
atv2_1 char(4),
atv2_2_2 char(4),
atv2_3 char(4),
resultado_av2 varchar(20),
resultado_usinadade1 varchar(20),
atv3_1 char(4),
atv3_2 char(4),
atv3_3_3 char(4),
resultado_av3 varchar(20),
atv4_1 char(4),
atv4_2 char(4),
atv4_3 char(4),
resultado_av4 varchar(20),
resultado_usinadade2 varchar(20),
atv5_1 char(4),
atv5_2 char(4),
atv5_3 char(4),
resultado_av5 varchar(20),
atv6_1 char(4),
atv6_2 char(4),
atv6_3 char(4),
resultado_av6 varchar(20),
resultado_usinadade3 varchar(20),
resultado_final varchar(50)
);


